project:
  type: website
  output-dir: docs
execute:
  freeze: auto
website:
  site-url: "https://intl-society-for-kaigo-research.github.io/home/index.html"
  title: "ISKR"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - event.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



