project:
  type: website
  output-dir: docs
execute:
  freeze: auto
website:
  site-url: "https://intl-society-for-kaigo-research.github.io/home/index.html"
  title: "ISKR"
  page-footer:
    left: "Copyright 2021, Norah Jones" 
    right: 
      - icon: github
        href: https://github.com/intl-society-for-kaigo-research
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - event.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



